_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 30
                - 41
                - 50
            "2":
                - 1
                - 30
                - 41
                - 50
            "3":
                - 16
                - 55
            "4": 3.12.3
            "5": 0.20.1
            "12": 0.20.1
            "13": linux-x86_64
batch_size:
    value: 64
epochs:
    value: 20
learning_rate:
    value: 0.001
