_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.12.4
        t:
            "1":
                - 1
                - 41
                - 50
            "2":
                - 1
                - 41
                - 50
            "3":
                - 16
                - 55
            "4": 3.12.4
            "5": 0.20.1
            "8":
                - 3
            "12": 0.20.1
            "13": windows-amd64
dataset:
    value:
        dataset:
            batch_size: 128
model:
    value:
        model:
            name: SmallMobileNet
trainer:
    value:
        trainer:
            epochs: 20
            lr: 0.01
            mixed_precision: true
