_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 30
                - 41
                - 50
            "2":
                - 1
                - 30
                - 41
                - 50
            "3":
                - 16
                - 55
            "4": 3.10.12
            "5": 0.20.1
            "12": 0.20.1
            "13": linux-x86_64
dataset:
    value:
        _target_: data.mnist.get_dataloaders
        batch_size: 32
        shuffle: true
model:
    value:
        _target_: models.small_mobilenet.SmallMobileNet
optimizer:
    value:
        _target_: torch.optim.Adam
        lr: 0.02055774776805891
trainer:
    value:
        epochs: 15
        mixed_precision: true
